In [1]:
from sklearn import datasets
from sklearn import linear_model as lm
from sklearn import model_selection as ms
import numpy as np
import random

In [2]:
data=datasets.load_boston()
data

{'data': array([[6.3200e-03, 1.8000e+01, 2.3100e+00, ..., 1.5300e+01, 3.9690e+02,
         4.9800e+00],
        [2.7310e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9690e+02,
         9.1400e+00],
        [2.7290e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9283e+02,
         4.0300e+00],
        ...,
        [6.0760e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
         5.6400e+00],
        [1.0959e-01, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9345e+02,
         6.4800e+00],
        [4.7410e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
         7.8800e+00]]),
 'target': array([24. , 21.6, 34.7, 33.4, 36.2, 28.7, 22.9, 27.1, 16.5, 18.9, 15. ,
        18.9, 21.7, 20.4, 18.2, 19.9, 23.1, 17.5, 20.2, 18.2, 13.6, 19.6,
        15.2, 14.5, 15.6, 13.9, 16.6, 14.8, 18.4, 21. , 12.7, 14.5, 13.2,
        13.1, 13.5, 18.9, 20. , 21. , 24.7, 30.8, 34.9, 26.6, 25.3, 24.7,
        21.2, 19.3, 20. , 16.6, 14.4, 19.4, 19.7, 20.5, 25. , 23.4, 18.9,
        35.4, 24.7, 3

In [3]:
x=data['data']
x

array([[6.3200e-03, 1.8000e+01, 2.3100e+00, ..., 1.5300e+01, 3.9690e+02,
        4.9800e+00],
       [2.7310e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9690e+02,
        9.1400e+00],
       [2.7290e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9283e+02,
        4.0300e+00],
       ...,
       [6.0760e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
        5.6400e+00],
       [1.0959e-01, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9345e+02,
        6.4800e+00],
       [4.7410e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
        7.8800e+00]])

In [4]:
y=data['target']
y

array([24. , 21.6, 34.7, 33.4, 36.2, 28.7, 22.9, 27.1, 16.5, 18.9, 15. ,
       18.9, 21.7, 20.4, 18.2, 19.9, 23.1, 17.5, 20.2, 18.2, 13.6, 19.6,
       15.2, 14.5, 15.6, 13.9, 16.6, 14.8, 18.4, 21. , 12.7, 14.5, 13.2,
       13.1, 13.5, 18.9, 20. , 21. , 24.7, 30.8, 34.9, 26.6, 25.3, 24.7,
       21.2, 19.3, 20. , 16.6, 14.4, 19.4, 19.7, 20.5, 25. , 23.4, 18.9,
       35.4, 24.7, 31.6, 23.3, 19.6, 18.7, 16. , 22.2, 25. , 33. , 23.5,
       19.4, 22. , 17.4, 20.9, 24.2, 21.7, 22.8, 23.4, 24.1, 21.4, 20. ,
       20.8, 21.2, 20.3, 28. , 23.9, 24.8, 22.9, 23.9, 26.6, 22.5, 22.2,
       23.6, 28.7, 22.6, 22. , 22.9, 25. , 20.6, 28.4, 21.4, 38.7, 43.8,
       33.2, 27.5, 26.5, 18.6, 19.3, 20.1, 19.5, 19.5, 20.4, 19.8, 19.4,
       21.7, 22.8, 18.8, 18.7, 18.5, 18.3, 21.2, 19.2, 20.4, 19.3, 22. ,
       20.3, 20.5, 17.3, 18.8, 21.4, 15.7, 16.2, 18. , 14.3, 19.2, 19.6,
       23. , 18.4, 15.6, 18.1, 17.4, 17.1, 13.3, 17.8, 14. , 14.4, 13.4,
       15.6, 11.8, 13.8, 15.6, 14.6, 17.8, 15.4, 21

In [5]:
def grad_error(x,y,m):
    grad=np.zeros(x.shape[1])
    for j in range(x.shape[1]):
        dedj=0
        for i in range(x.shape[0]):
            dedj+=2*((m*x[i,:]).sum()-y[i])*x[i,j]
        grad[j]=dedj
    return grad

In [6]:
def cost(x,y,m):
    cost=0
    for i in range(x.shape[0]):
        cost+=(y[i]-(m*x[i,:]).sum())**2
    return cost

In [7]:
def grad_decent(x,y,lr,max):
    length=x.shape[1]
    m=np.zeros(length)
    for i in range(max):
        m-=lr*grad_error(x,y,m)
    return m

In [27]:
def init_lr(x,y,m,grad):
    lr=0.1
    while cost(x,y,m-lr*grad)>cost(x,y,m-1.1*lr*grad):
        lr*=2
    return lr

In [40]:
def update(x,y,m,grad,lr):
    lr0=0
    lrmax=lr
    while lrmax>1.1*lr0:
        lrmean=(lr0+lrmax)/2
        lr1=lr0+0.25*(lrmax-lr0)
        lr3=lr0+0.75*(lrmax-lr0)
        #print(lr0,lr1,lrmean,lr3,lrmax)
        if cost(x,y,m-lr1*grad)>cost(x,y,m-lr3*grad):
            lr0=lrmean
        else:
            lrmax=lrmean
    #print(lr0,lrmax)
    m-=lr0*grad
    return m

In [75]:
def grads_decent(x,y,max):
    length=x.shape[1]
    m=np.zeros(length)
    mn=np.zeros(length)
    i=0
    while (((mn*mn).sum()>1.001*((m*m).sum())) or ((mn*mn).sum()<1.001*((m*m).sum())) or i==0) and i<max:
        m=mn
        grad=grad_error(x,y,m)
        #print(grad)
        lr0=init_lr(x,y,m,grad)
        #print(lr0)
        mn=update(x,y,m,grad,lr0)
        i+=1
    print(i)
    return mn

In [87]:
grad_decent(np.array([[2,3,1],[-1,3,1],[0,2,1],[-5,1,1]]),np.array([2,4,3,-1]),.03,100)

array([ 0.15288126,  1.30987787, -0.76372436])

In [80]:
grads_decent(np.array([[2,3,1],[-1,3,1],[0,2,1],[-5,1,1]]),np.array([2,4,3,-1]),1000)

1000


array([ 0.03354955,  1.73258509, -1.86472732])

In [13]:
x_model=np.array([[2,3,1],[-1,3,1],[0,2,1],[-5,1,1]])
y_model=np.array([2,4,3,-1])
algo=lm.LinearRegression()
algo.fit(x_model,y_model)
algo.coef_


array([0.03333333, 1.73333333, 0.        ])

In [14]:
algo.intercept_

-1.8666666666666707

In [15]:
x_1=np.ones([x.shape[0],x.shape[1]+1])
for i in range(x.shape[0]):
    for j in range(x.shape[1]):
        x_1[i,j]=x[i,j]
x_1

array([[6.3200e-03, 1.8000e+01, 2.3100e+00, ..., 3.9690e+02, 4.9800e+00,
        1.0000e+00],
       [2.7310e-02, 0.0000e+00, 7.0700e+00, ..., 3.9690e+02, 9.1400e+00,
        1.0000e+00],
       [2.7290e-02, 0.0000e+00, 7.0700e+00, ..., 3.9283e+02, 4.0300e+00,
        1.0000e+00],
       ...,
       [6.0760e-02, 0.0000e+00, 1.1930e+01, ..., 3.9690e+02, 5.6400e+00,
        1.0000e+00],
       [1.0959e-01, 0.0000e+00, 1.1930e+01, ..., 3.9345e+02, 6.4800e+00,
        1.0000e+00],
       [4.7410e-02, 0.0000e+00, 1.1930e+01, ..., 3.9690e+02, 7.8800e+00,
        1.0000e+00]])

In [77]:
grads_decent(x_1,y,300)

300


array([-0.121404  ,  0.12400845, -0.08042053,  0.01235694,  0.00695424,
        0.21684871,  0.09920803,  0.02739283,  0.02544677,  0.00504323,
        0.15188067,  0.04235043, -0.51009861,  0.01874539])

In [42]:
algo.fit(x,y)
algo.coef_

array([-1.08011358e-01,  4.64204584e-02,  2.05586264e-02,  2.68673382e+00,
       -1.77666112e+01,  3.80986521e+00,  6.92224640e-04, -1.47556685e+00,
        3.06049479e-01, -1.23345939e-02, -9.52747232e-01,  9.31168327e-03,
       -5.24758378e-01])

In [72]:
algo.intercept_

36.459488385089884

In [78]:
cost(x_1,y,np.array([-1.08011358e-01,  4.64204584e-02,  2.05586264e-02,  2.68673382e+00,
       -1.77666112e+01,  3.80986521e+00,  6.92224640e-04, -1.47556685e+00,
        3.06049479e-01, -1.23345939e-02, -9.52747232e-01,  9.31168327e-03,
       -5.24758378e-01,36.459488385089884]))

11078.784577954964

In [79]:
cost(x_1,y,np.array([-0.121404  ,  0.12400845, -0.08042053,  0.01235694,  0.00695424,
        0.21684871,  0.09920803,  0.02739283,  0.02544677,  0.00504323,
        0.15188067,  0.04235043, -0.51009861,  0.01874539]))

26418.796045860425