## Logistic regression with gradient decent on iris data

In [1]:
import numpy as np
from sklearn import datasets
from sklearn import model_selection
from sklearn import linear_model as lm
import pandas as pd
import random

In [2]:
data=datasets.load_iris()
data

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

In [3]:
x=data.data
y=data.target

In [4]:
x.shape

(150, 4)

In [5]:
y.shape

(150,)

In [6]:
x,x_test,y,y_test= model_selection.train_test_split(x,y)

### Data manipulation for one vs rest approach

In [7]:
print(x.shape)
print(y.shape)
print(x_test.shape)
dfy=pd.Series(y)

(112, 4)
(112,)
(38, 4)


In [8]:
dfy=dfy.replace({2:1})
y=dfy.values
y

array([1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1,
       1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0,
       0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0,
       0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1,
       1, 0], dtype=int64)

### Standardization

In [9]:
[d0,d1]=x.shape
[dt0,dt1]=x_test.shape
norm=np.zeros([2,d1])

In [10]:
for i in range(d1):
    norm[0,i]=x[:,i].mean()
    norm[1,i]=np.sqrt(x[:,i].var())
    x[:,i]=(x[:,i]-norm[0,i])/norm[1,i]
x

array([[ 1.83591511, -0.57477309,  1.32245449,  0.95360845],
       [ 0.65077106,  0.09347521,  0.97959592,  0.81841333],
       [-1.0084306 ,  1.20722236, -1.36327098, -1.34470863],
       [-1.24545941, -0.12927422, -1.36327098, -1.20951351],
       [ 0.41374225,  0.7617235 ,  0.92245282,  1.49438894],
       [-1.48248822,  0.7617235 , -1.36327098, -1.20951351],
       [ 0.17671344, -1.91126967,  0.12244949, -0.26314765],
       [-1.36397382,  0.31622464, -1.42041408, -1.34470863],
       [ 0.65077106, -0.57477309,  1.03673901,  1.35919382],
       [-1.0084306 ,  0.7617235 , -1.30612789, -1.34470863],
       [-0.53437298,  0.7617235 , -1.30612789, -1.07431838],
       [ 0.29522785, -0.12927422,  0.63673735,  0.81841333],
       [-0.65288739,  1.42997179, -1.30612789, -1.34470863],
       [ 0.53225666, -1.24302138,  0.69388044,  0.95360845],
       [-0.8899162 ,  1.65272123, -1.07755551, -1.07431838],
       [ 0.65077106,  0.31622464,  0.40816497,  0.41282796],
       [-1.0084306 ,  0.

In [11]:
for i in range(d1):
    x_test[:,i]=(x_test[:,i]-norm[0,i])/norm[1,i]
x_test

array([[ 0.76928547, -0.12927422,  0.80816663,  1.08880357],
       [-0.17882977, -1.24302138,  0.69388044,  1.08880357],
       [-0.17882977, -0.12927422,  0.23673568,  0.0072426 ],
       [ 1.5988863 , -0.12927422,  1.1510252 ,  0.54802309],
       [ 0.53225666, -1.68852024,  0.35102187,  0.14243772],
       [ 1.24334308,  0.09347521,  0.75102354,  1.49438894],
       [-1.0084306 ,  0.31622464, -1.47755717, -1.34470863],
       [ 0.53225666,  0.53897407,  1.26531139,  1.76477919],
       [-0.06031537, -0.57477309,  0.75102354,  1.62958406],
       [-0.29734418, -0.57477309,  0.63673735,  1.08880357],
       [-0.41585858, -1.46577081, -0.0489798 , -0.26314765],
       [ 1.00631427, -0.12927422,  0.80816663,  1.49438894],
       [ 0.76928547, -0.12927422,  0.97959592,  0.81841333],
       [ 0.29522785, -0.12927422,  0.46530806,  0.27763284],
       [-0.53437298,  1.87547066, -1.42041408, -1.07431838],
       [-0.41585858, -1.24302138,  0.12244949,  0.14243772],
       [ 0.17671344, -0.

In [12]:
xdf=pd.DataFrame(x)
xdf[d1]=np.ones(d0)
x=xdf.values
x

array([[ 1.83591511, -0.57477309,  1.32245449,  0.95360845,  1.        ],
       [ 0.65077106,  0.09347521,  0.97959592,  0.81841333,  1.        ],
       [-1.0084306 ,  1.20722236, -1.36327098, -1.34470863,  1.        ],
       [-1.24545941, -0.12927422, -1.36327098, -1.20951351,  1.        ],
       [ 0.41374225,  0.7617235 ,  0.92245282,  1.49438894,  1.        ],
       [-1.48248822,  0.7617235 , -1.36327098, -1.20951351,  1.        ],
       [ 0.17671344, -1.91126967,  0.12244949, -0.26314765,  1.        ],
       [-1.36397382,  0.31622464, -1.42041408, -1.34470863,  1.        ],
       [ 0.65077106, -0.57477309,  1.03673901,  1.35919382,  1.        ],
       [-1.0084306 ,  0.7617235 , -1.30612789, -1.34470863,  1.        ],
       [-0.53437298,  0.7617235 , -1.30612789, -1.07431838,  1.        ],
       [ 0.29522785, -0.12927422,  0.63673735,  0.81841333,  1.        ],
       [-0.65288739,  1.42997179, -1.30612789, -1.34470863,  1.        ],
       [ 0.53225666, -1.24302138,  0.6

In [13]:
xtdf=pd.DataFrame(x_test)
xtdf[d1]=np.ones(dt0)
x_test=xtdf.values
x_test

array([[ 0.76928547, -0.12927422,  0.80816663,  1.08880357,  1.        ],
       [-0.17882977, -1.24302138,  0.69388044,  1.08880357,  1.        ],
       [-0.17882977, -0.12927422,  0.23673568,  0.0072426 ,  1.        ],
       [ 1.5988863 , -0.12927422,  1.1510252 ,  0.54802309,  1.        ],
       [ 0.53225666, -1.68852024,  0.35102187,  0.14243772,  1.        ],
       [ 1.24334308,  0.09347521,  0.75102354,  1.49438894,  1.        ],
       [-1.0084306 ,  0.31622464, -1.47755717, -1.34470863,  1.        ],
       [ 0.53225666,  0.53897407,  1.26531139,  1.76477919,  1.        ],
       [-0.06031537, -0.57477309,  0.75102354,  1.62958406,  1.        ],
       [-0.29734418, -0.57477309,  0.63673735,  1.08880357,  1.        ],
       [-0.41585858, -1.46577081, -0.0489798 , -0.26314765,  1.        ],
       [ 1.00631427, -0.12927422,  0.80816663,  1.49438894,  1.        ],
       [ 0.76928547, -0.12927422,  0.97959592,  0.81841333,  1.        ],
       [ 0.29522785, -0.12927422,  0.4

### Gradient decent for logistic regression

In [14]:
def grad_point(x,y,m,C):
    gx=(m*x).sum()
    hx=1/(1+np.exp(-gx))
    m1=m
    m1[-1]=0
    return C*(hx-y)*x+2*m1

In [15]:
def grad(x,y,m,C,batch):
    [d0,d1]=x.shape
    grad=np.zeros(d1)
    for i in random.sample(range(d0),batch):
        grad+=grad_point(x[i,:],y[i],m,C)
    return grad/batch

In [16]:
def logistic_regression(x,y,lr,C,max_iter,batch):
    [d0,d1]=x.shape
    m=np.zeros(d1)
    for i in range(max_iter):
        m-=lr*grad(x,y,m,C,batch)
    return m

In [17]:
def predict(x,m):
    [d0,d1]=x.shape
    y=np.zeros(d0)
    for i in range(d0):
        gx=(x[i,:]*m).sum()
        y[i]=1 if 1/(1+np.exp(-gx))>0.5 else 0
    return y

In [18]:
[d0,d1]=x.shape
[dt0,dt1]=x_test.shape

### Implementation

In [19]:
m=logistic_regression(x,y,.01,1,10,70)
print(m)

[ 0.03024985 -0.02555922  0.03875946  0.03741932  0.0015821 ]


In [20]:
y_predict=predict(x_test,m)

In [21]:
from sklearn import metrics

In [22]:
print(y_predict)
print(y_test)

[1. 1. 1. 1. 1. 1. 0. 1. 1. 1. 1. 1. 1. 1. 0. 1. 1. 0. 1. 0. 0. 1. 0. 0.
 1. 1. 0. 0. 1. 0. 1. 1. 1. 0. 0. 0. 0. 1.]
[2 2 1 2 1 2 0 2 2 2 1 2 2 1 0 1 2 0 2 0 0 2 0 0 2 1 0 0 2 0 1 1 1 0 0 0 0
 1]


In [23]:
ydf_test=pd.Series(y_test)
ydf_test=ydf_test.replace({2:1})

In [24]:
y_test=ydf_test.values
print(ydf_test)

0     1
1     1
2     1
3     1
4     1
5     1
6     0
7     1
8     1
9     1
10    1
11    1
12    1
13    1
14    0
15    1
16    1
17    0
18    1
19    0
20    0
21    1
22    0
23    0
24    1
25    1
26    0
27    0
28    1
29    0
30    1
31    1
32    1
33    0
34    0
35    0
36    0
37    1
dtype: int64


In [25]:
metrics.confusion_matrix(y_test,y_predict)

array([[14,  0],
       [ 0, 24]], dtype=int64)

In [26]:
print(metrics.classification_report(y_test,y_predict))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        14
           1       1.00      1.00      1.00        24

    accuracy                           1.00        38
   macro avg       1.00      1.00      1.00        38
weighted avg       1.00      1.00      1.00        38

