## Logistic Regression on Titanic dataset

In [1]:
import numpy as np
from sklearn import linear_model as lm
from sklearn import metrics
import pandas as pd
#from sklearn import datasets

In [2]:
df=pd.read_csv('Downloads/titanic_x_y_train.csv')
df_test=pd.read_csv('Downloads/titanic_x_test.csv')
df_test

Pclass                                               Name     Sex   Age  \
0         2                     Davies, Master. John Morgan Jr    male   8.0   
1         1                        Leader, Dr. Alice (Farnham)  female  49.0   
2         3                            Kilgannon, Mr. Thomas J    male   NaN   
3         2  Jacobsohn, Mrs. Sidney Samuel (Amy Frances Chr...  female  24.0   
4         1                          McGough, Mr. James Robert    male  36.0   
..      ...                                                ...     ...   ...   
218       3                        Lindqvist, Mr. Eino William    male  20.0   
219       1                  Butt, Major. Archibald Willingham    male  45.0   
220       1  Penasco y Castellana, Mrs. Victor de Satode (M...  female  17.0   
221       3                   Holm, Mr. John Fredrik Alexander    male  43.0   
222       2           Navratil, Mr. Michel ("Louis M Hoffman")    male  36.5   

     SibSp  Parch             Ticket      Fare Cabin Embarked  
0        1      1         C.A. 33112   36.7500   NaN        S  
1        0      0              17465   25.9292   D17        S  
2        0      0              36865    7.7375   NaN        Q  
3        2      1             243847   27.0000   NaN        S  
4        0      0           PC 17473   26.2875   E25        S  
..     ...    ...                ...       ...   ...      ...  
218      1      0  STON/O 2. 3101285    7.9250   NaN        S  
219      0      0             113050   26.5500   B38        S  
220      1      0           PC 17758  108.9000   C65        C  
221      0      0             C 7075    6.4500   NaN        S  
222      0      2             230080   26.0000    F2        S  

[223 rows x 10 columns]

### Droping features with missing values

In [3]:
df1=df.drop(['Name','Ticket','Cabin','Age','Embarked'],axis=1)
df_test=df_test.drop(['Name','Ticket','Cabin','Age','Embarked'],axis=1)
df1

Pclass     Sex  SibSp  Parch     Fare  Survived
0         2  female      1      0  26.0000         1
1         3    male      0      0   8.0500         0
2         2    male      0      0  26.0000         0
3         3  female      0      4  21.0750         0
4         3    male      0      0   7.0500         0
..      ...     ...    ...    ...      ...       ...
663       2  female      0      0  10.5000         1
664       3    male      0      0   7.7500         0
665       3    male      0      0  56.4958         1
666       3  female      0      0   9.8375         0
667       3  female      1      0  15.5000         1

[668 rows x 6 columns]

In [4]:
df2=df1.dropna()
df2.shape
df_test.info

<bound method DataFrame.info of      Pclass     Sex  SibSp  Parch      Fare
0         2    male      1      1   36.7500
1         1  female      0      0   25.9292
2         3    male      0      0    7.7375
3         2  female      2      1   27.0000
4         1    male      0      0   26.2875
..      ...     ...    ...    ...       ...
218       3    male      1      0    7.9250
219       1    male      0      0   26.5500
220       1  female      1      0  108.9000
221       3    male      0      0    6.4500
222       2    male      0      2   26.0000

[223 rows x 5 columns]>

In [5]:
df2['Sex']=df2['Sex'].map({'female':-1,'male':1})
df_test['Sex']=df_test['Sex'].map({'female':-1,'male':1})
y=df2['Survived'].values
df2=df2.drop(['Survived'],axis=1)
df2

Pclass  Sex  SibSp  Parch     Fare
0         2   -1      1      0  26.0000
1         3    1      0      0   8.0500
2         2    1      0      0  26.0000
3         3   -1      0      4  21.0750
4         3    1      0      0   7.0500
..      ...  ...    ...    ...      ...
663       2   -1      0      0  10.5000
664       3    1      0      0   7.7500
665       3    1      0      0  56.4958
666       3   -1      0      0   9.8375
667       3   -1      1      0  15.5000

[668 rows x 5 columns]

### Composite Feature creation

In [6]:
d1=df2.shape[1]
for i in range(d1):
    for j in range(i,d1):
        if (df2.iloc[:,i]*df2.iloc[:,j]).var()==0:
            pass
        else:
            df2[str(i)+str(j)]=df2.iloc[:,i]*df2.iloc[:,j]

d2=df2.shape[1]
for i in range(d1):
    for j in range(i,d2):
        if (df2.iloc[:,i]*df2.iloc[:,j]).var()==0:
            pass
        else:
            df2[str(i)+str(j)]=df2.iloc[:,i]*df2.iloc[:,j]
d3=df2.shape[1]
for i in range(d1):
    for j in range(i,d3):
        if (df2.iloc[:,i]*df2.iloc[:,j]).var()==0:
            pass
        else:
            df2[str(i)+str(j)]=df2.iloc[:,i]*df2.iloc[:,j]
df2.shape

(668, 439)

In [7]:
for i in range(d1):
    for j in range(i,d1):
        df_test[str(i)+str(j)]=df_test.iloc[:,i]*df_test.iloc[:,j]
for i in range(d1):
    for j in range(i,d2):
        df_test[str(i)+str(j)]=df_test.iloc[:,i]*df_test.iloc[:,j]
for i in range(d1):
    for j in range(i,d3):
        df_test[str(i)+str(j)]=df_test.iloc[:,i]*df_test.iloc[:,j]
df_test.shape 

(223, 440)

In [8]:
df_test=df_test[df2.columns]
df_test.shape

(223, 439)

In [9]:
df2

Pclass  Sex  SibSp  Parch     Fare  00  01  02  03        04  ...  \
0         2   -1      1      0  26.0000   4  -2   2   0   52.0000  ...   
1         3    1      0      0   8.0500   9   3   0   0   24.1500  ...   
2         2    1      0      0  26.0000   4   2   0   0   52.0000  ...   
3         3   -1      0      4  21.0750   9  -3   0  12   63.2250  ...   
4         3    1      0      0   7.0500   9   3   0   0   21.1500  ...   
..      ...  ...    ...    ...      ...  ..  ..  ..  ..       ...  ...   
663       2   -1      0      0  10.5000   4  -2   0   0   21.0000  ...   
664       3    1      0      0   7.7500   9   3   0   0   23.2500  ...   
665       3    1      0      0  56.4958   9   3   0   0  169.4874  ...   
666       3   -1      0      0   9.8375   9  -3   0   0   29.5125  ...   
667       3   -1      1      0  15.5000   9  -3   3   0   46.5000  ...   

               479     480        481            482     483  484        485  \
0     35152.000000 -676.00     0.0000  -17576.000000  676.00  0.0  17576.000   
1      1564.980375    0.00     0.0000     521.660125    0.00  0.0      0.000   
2     35152.000000    0.00     0.0000   17576.000000    0.00  0.0      0.000   
3     28081.739391    0.00 -1776.6225   -9360.579797    0.00  0.0      0.000   
4      1051.207875    0.00     0.0000     350.402625    0.00  0.0      0.000   
..             ...     ...        ...            ...     ...  ...        ...   
663    2315.250000    0.00     0.0000   -1157.625000    0.00  0.0      0.000   
664    1396.453125    0.00     0.0000     465.484375    0.00  0.0      0.000   
665  540965.716920    0.00     0.0000  180321.905640    0.00  0.0      0.000   
666    2856.113689    0.00     0.0000    -952.037896    0.00  0.0      0.000   
667   11171.625000 -240.25     0.0000   -3723.875000  240.25  0.0   3723.875   

         486           487           488  
0       0.00      0.000000  4.569760e+05  
1       0.00      0.000000  4.199364e+03  
2       0.00      0.000000  4.569760e+05  
3    7106.49  37442.319187  1.972742e+05  
4       0.00      0.000000  2.470339e+03  
..       ...           ...           ...  
663     0.00      0.000000  1.215506e+04  
664     0.00      0.000000  3.607504e+03  
665     0.00      0.000000  1.018743e+07  
666     0.00      0.000000  9.365673e+03  
667     0.00      0.000000  5.772006e+04  

[668 rows x 439 columns]

In [10]:
x=df2.values
x_test=df_test.values

In [11]:
print(x.shape)
print(y.shape)

(668, 439)
(668,)


### Standardization

In [12]:
norm=np.zeros([2,x.shape[1]])
for i in range(x.shape[1]):
    norm[0,i]=x[:,i].mean()
    norm[1,i]=np.sqrt(x[:,i].var())
    x[:,i]=(x[:,i]-norm[0,i])/norm[1,i]
x

array([[-0.35668092, -1.33108386,  0.43682178, ..., -0.11047659,
        -0.11123931, -0.0666834 ],
       [ 0.84666683,  0.75126747, -0.48951775, ..., -0.11047659,
        -0.11123931, -0.06685108],
       [-0.35668092,  0.75126747, -0.48951775, ..., -0.11047659,
        -0.11123931, -0.0666834 ],
       ...,
       [ 0.84666683,  0.75126747, -0.48951775, ..., -0.11047659,
        -0.11123931, -0.06307978],
       [ 0.84666683, -1.33108386, -0.48951775, ..., -0.11047659,
        -0.11123931, -0.06684917],
       [ 0.84666683, -1.33108386,  0.43682178, ..., -0.11047659,
        -0.11123931, -0.06683126]])

In [13]:
for i in range(x_test.shape[1]):
    x_test[:,i]=(x_test[:,i]-norm[0,i])/norm[1,i]

In [14]:
y

array([1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0,
       1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1,
       0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0,
       0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1,
       0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0,
       1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1,
       1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1,
       0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0,
       1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1,
       1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1,

### Logistic Regression

In [15]:
algo=lm.LogisticRegression(solver='saga',max_iter=2000)
algo.fit(x,y)
#y_pred=algo.predict(x)
#algo.score(y,y_pred)
#mat=metrics.confusion_matrix(y,y_pred)
#mat

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=2000,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='saga', tol=0.0001, verbose=0,
                   warm_start=False)

In [16]:
y_pred=algo.predict(x_test)

In [17]:
y_pred

array([1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0,
       1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0,
       1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1,
       0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0,
       0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0,
       0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0,
       1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0,
       1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0,
       0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1,
       1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1,
       1, 0, 1], dtype=int64)

In [18]:
np.savetxt('Downloads/titanic_y_pred.csv',y_pred,delimiter=',')

In [1]:
### only 62.8% accuracy achived as per judgement