## Logistic regression with gradient decent on iris data

In [25]:
import numpy as np
from sklearn import datasets
from sklearn import model_selection
from sklearn import linear_model as lm
import pandas as pd
import random

In [26]:
data=datasets.load_iris()
data

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

In [27]:
x=data.data
y=data.target

In [28]:
x.shape

(150, 4)

In [29]:
y.shape

(150,)

In [30]:
x,x_test,y,y_test= model_selection.train_test_split(x,y)

### Data manipulation for one vs rest approach

In [31]:
print(x.shape)
print(y.shape)
print(x_test.shape)
dfy=pd.Series(y)

(112, 4)
(112,)
(38, 4)


In [32]:
dfy=dfy.replace({2:1})
y=dfy.values
y

array([0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1,
       1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0,
       0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       1, 1], dtype=int64)

### Standardization

In [33]:
[d0,d1]=x.shape
[dt0,dt1]=x_test.shape
norm=np.zeros([2,d1])

In [34]:
for i in range(d1):
    norm[0,i]=x[:,i].mean()
    norm[1,i]=np.sqrt(x[:,i].var())
    x[:,i]=(x[:,i]-norm[0,i])/norm[1,i]
x

array([[-2.35557712e-01,  3.05757207e+00, -1.39638948e+00,
        -1.15927128e+00],
       [-9.75252955e-01,  1.01378384e+00, -1.45452912e+00,
        -1.29594326e+00],
       [ 6.27420073e-01, -8.02916803e-01,  8.12916702e-01,
         8.90808454e-01],
       [-4.82122793e-01, -1.48417955e+00, -1.17317481e-01,
        -3.39239384e-01],
       [-2.35557712e-01, -5.75829223e-01,  1.15241065e-01,
         7.07765621e-02],
       [ 3.80854992e-01, -5.75829223e-01,  5.22218520e-01,
         7.54136472e-01],
       [-1.09853550e+00,  7.86696262e-01, -1.39638948e+00,
        -1.43261524e+00],
       [ 3.80854992e-01,  7.86696262e-01,  8.71056338e-01,
         1.43749638e+00],
       [-6.05405333e-01, -1.21654061e-01,  3.47799611e-01,
         3.44120526e-01],
       [-1.59166566e+00,  1.05433520e-01, -1.39638948e+00,
        -1.43261524e+00],
       [-1.12275171e-01, -8.02916803e-01, -1.03820779e-03,
        -6.58954199e-02],
       [ 9.97267695e-01,  1.05433520e-01,  2.89659974e-01,
      

In [35]:
for i in range(d1):
    x_test[:,i]=(x_test[:,i]-norm[0,i])/norm[1,i]
x_test

array([[-1.09853550e+00, -1.21654061e-01, -1.33824985e+00,
        -1.43261524e+00],
       [ 1.61368040e+00,  1.24087142e+00,  1.27803379e+00,
         1.71084035e+00],
       [ 1.86024548e+00, -5.75829223e-01,  1.27803379e+00,
         8.90808454e-01],
       [-8.51970415e-01,  7.86696262e-01, -1.45452912e+00,
        -1.43261524e+00],
       [-1.12275171e-01, -1.03000438e+00,  5.71014286e-02,
        -6.58954199e-02],
       [-7.28687874e-01,  1.46795900e+00, -1.39638948e+00,
        -1.43261524e+00],
       [ 1.10073697e-02, -1.21654061e-01,  6.96637429e-01,
         7.54136472e-01],
       [ 5.04137532e-01, -1.25709196e+00,  5.80358156e-01,
         3.44120526e-01],
       [-9.75252955e-01,  7.86696262e-01, -1.39638948e+00,
        -1.43261524e+00],
       [-1.59166566e+00,  3.32521100e-01, -1.45452912e+00,
        -1.43261524e+00],
       [ 9.97267695e-01,  5.59608681e-01,  1.04547525e+00,
         1.71084035e+00],
       [ 6.27420073e-01, -5.75829223e-01,  9.87335611e-01,
      

In [36]:
xdf=pd.DataFrame(x)
xdf[d1]=np.ones(d0)
x=xdf.values
x

array([[-2.35557712e-01,  3.05757207e+00, -1.39638948e+00,
        -1.15927128e+00,  1.00000000e+00],
       [-9.75252955e-01,  1.01378384e+00, -1.45452912e+00,
        -1.29594326e+00,  1.00000000e+00],
       [ 6.27420073e-01, -8.02916803e-01,  8.12916702e-01,
         8.90808454e-01,  1.00000000e+00],
       [-4.82122793e-01, -1.48417955e+00, -1.17317481e-01,
        -3.39239384e-01,  1.00000000e+00],
       [-2.35557712e-01, -5.75829223e-01,  1.15241065e-01,
         7.07765621e-02,  1.00000000e+00],
       [ 3.80854992e-01, -5.75829223e-01,  5.22218520e-01,
         7.54136472e-01,  1.00000000e+00],
       [-1.09853550e+00,  7.86696262e-01, -1.39638948e+00,
        -1.43261524e+00,  1.00000000e+00],
       [ 3.80854992e-01,  7.86696262e-01,  8.71056338e-01,
         1.43749638e+00,  1.00000000e+00],
       [-6.05405333e-01, -1.21654061e-01,  3.47799611e-01,
         3.44120526e-01,  1.00000000e+00],
       [-1.59166566e+00,  1.05433520e-01, -1.39638948e+00,
        -1.43261524e+00

In [37]:
xtdf=pd.DataFrame(x_test)
xtdf[d1]=np.ones(dt0)
x_test=xtdf.values
x_test

array([[-1.09853550e+00, -1.21654061e-01, -1.33824985e+00,
        -1.43261524e+00,  1.00000000e+00],
       [ 1.61368040e+00,  1.24087142e+00,  1.27803379e+00,
         1.71084035e+00,  1.00000000e+00],
       [ 1.86024548e+00, -5.75829223e-01,  1.27803379e+00,
         8.90808454e-01,  1.00000000e+00],
       [-8.51970415e-01,  7.86696262e-01, -1.45452912e+00,
        -1.43261524e+00,  1.00000000e+00],
       [-1.12275171e-01, -1.03000438e+00,  5.71014286e-02,
        -6.58954199e-02,  1.00000000e+00],
       [-7.28687874e-01,  1.46795900e+00, -1.39638948e+00,
        -1.43261524e+00,  1.00000000e+00],
       [ 1.10073697e-02, -1.21654061e-01,  6.96637429e-01,
         7.54136472e-01,  1.00000000e+00],
       [ 5.04137532e-01, -1.25709196e+00,  5.80358156e-01,
         3.44120526e-01,  1.00000000e+00],
       [-9.75252955e-01,  7.86696262e-01, -1.39638948e+00,
        -1.43261524e+00,  1.00000000e+00],
       [-1.59166566e+00,  3.32521100e-01, -1.45452912e+00,
        -1.43261524e+00

### Gradient decent for logistic regression

In [38]:
def grad_point(x,y,m,C):
    gx=(m*x).sum()
    hx=1/(1+np.exp(-gx))
    return C*(hx-y)*x+2*m

In [39]:
def grad(x,y,m,C,batch):
    [d0,d1]=x.shape
    grad=np.zeros(d1)
    for i in random.sample(range(d0),batch):
        grad+=grad_point(x[i,:],y[i],m,C)
    return grad/batch

In [40]:
def logistic_regression(x,y,lr,C,max_iter,batch):
    [d0,d1]=x.shape
    m=np.zeros(d1)
    for i in range(max_iter):
        m-=lr*grad(x,y,m,C,batch)
    return m

In [41]:
def predict(x,m):
    [d0,d1]=x.shape
    y=np.zeros(d0)
    for i in range(d0):
        gx=(x[i,:]*m).sum()
        y[i]=1 if 1/(1+np.exp(-gx))>0.5 else 0
    return y

In [42]:
[d0,d1]=x.shape
[dt0,dt1]=x_test.shape

### Implementation

In [43]:
m=logistic_regression(x,y,.01,1,10,70)
print(m)

[ 0.02872963 -0.02589339  0.03719272  0.03613864  0.01811805]


In [44]:
y_predict=predict(x_test,m)

In [45]:
from sklearn import metrics

In [46]:
print(y_predict)
print(y_test)

[0. 1. 1. 0. 1. 0. 1. 1. 0. 0. 1. 1. 1. 1. 0. 1. 0. 0. 1. 0. 0. 0. 0. 1.
 0. 0. 1. 1. 1. 0. 1. 1. 0. 1. 1. 1. 1. 0.]
[0 2 2 0 1 0 2 1 0 0 2 2 1 2 0 2 0 0 2 0 0 0 0 2 0 0 1 2 1 0 1 1 0 1 2 1 1
 0]


In [52]:
ydf_test=pd.Series(y_test)
ydf_test=ydf_test.replace({2:1})

In [54]:
y_test=ydf_test.values
print(ydf_test)

0     0
1     1
2     1
3     0
4     1
5     0
6     1
7     1
8     0
9     0
10    1
11    1
12    1
13    1
14    0
15    1
16    0
17    0
18    1
19    0
20    0
21    0
22    0
23    1
24    0
25    0
26    1
27    1
28    1
29    0
30    1
31    1
32    0
33    1
34    1
35    1
36    1
37    0
dtype: int64


In [55]:
metrics.confusion_matrix(y_test,y_predict)

array([[17,  0],
       [ 0, 21]], dtype=int64)

In [56]:
print(metrics.classification_report(y_test,y_predict))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        17
           1       1.00      1.00      1.00        21

    accuracy                           1.00        38
   macro avg       1.00      1.00      1.00        38
weighted avg       1.00      1.00      1.00        38

